spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: mongo
      port: 27017
      database: oauth-dbs

server:
  port: 8011
  servlet:
    context-path: /uaa
logging:
  level:
    org.springframework: INFO
