spring:
  application:
    name: auth-service
  data:
    mongodb:
      host: my-release-mongodb
      port: 27017
      username: oauth-user
      password: password
      database: oauth-db
  logging:
    level:
      org.springframework: DEBUG
server:
  servlet:
    context-path: /uaa
  port: 8011
