spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      username: oauth-user
      password: password
      database: oauth-db
  logging:
    level:
      org.springframework: DEBUG
server:
  servlet:
    context-path: /uaa
  port: 8781

